// This file is generated by ttrpc-compiler 0.8.0. Do not edit
// @generated

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unknown_lints)]
#![allow(clipto_camel_casepy)]
#![allow(dead_code)]
#![allow(missing_docs)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(trivial_casts)]
#![allow(unsafe_code)]
#![allow(unused_imports)]
#![allow(unused_results)]
#![allow(clippy::all)]
use protobuf::{CodedInputStream, CodedOutputStream, Message};
use std::collections::HashMap;
use std::sync::Arc;

#[derive(Clone)]
pub struct AetherAgentClient {
    client: ::ttrpc::Client,
}

impl AetherAgentClient {
    pub fn new(client: ::ttrpc::Client) -> Self {
        AetherAgentClient {
            client,
        }
    }

    pub fn register_add_in(&self, ctx: ttrpc::context::Context, req: &super::aether::AddInRequest) -> ::ttrpc::Result<super::aether::AddInResponse> {
        let mut cres = super::aether::AddInResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "aether.AetherAgent", "RegisterAddIn", cres);
        Ok(cres)
    }

    pub fn materialize_path(&self, ctx: ttrpc::context::Context, req: &super::aether::MaterializeRequest) -> ::ttrpc::Result<super::aether::MaterializeResponse> {
        let mut cres = super::aether::MaterializeResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "aether.AetherAgent", "MaterializePath", cres);
        Ok(cres)
    }

    pub fn update_proxy_rules(&self, ctx: ttrpc::context::Context, req: &super::aether::ProxyRules) -> ::ttrpc::Result<super::empty::Empty> {
        let mut cres = super::empty::Empty::new();
        ::ttrpc::client_request!(self, ctx, req, "aether.AetherAgent", "UpdateProxyRules", cres);
        Ok(cres)
    }

    pub fn get_manifest(&self, ctx: ttrpc::context::Context, req: &super::aether::GetManifestRequest) -> ::ttrpc::Result<super::aether::ManifestResponse> {
        let mut cres = super::aether::ManifestResponse::new();
        ::ttrpc::client_request!(self, ctx, req, "aether.AetherAgent", "GetManifest", cres);
        Ok(cres)
    }

}

struct RegisterAddInMethod {
    service: Arc<dyn AetherAgent + Send + Sync>,
}

impl ::ttrpc::MethodHandler for RegisterAddInMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, aether, AddInRequest, register_add_in);
        Ok(())
    }
}

struct MaterializePathMethod {
    service: Arc<dyn AetherAgent + Send + Sync>,
}

impl ::ttrpc::MethodHandler for MaterializePathMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, aether, MaterializeRequest, materialize_path);
        Ok(())
    }
}

struct UpdateProxyRulesMethod {
    service: Arc<dyn AetherAgent + Send + Sync>,
}

impl ::ttrpc::MethodHandler for UpdateProxyRulesMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, aether, ProxyRules, update_proxy_rules);
        Ok(())
    }
}

struct GetManifestMethod {
    service: Arc<dyn AetherAgent + Send + Sync>,
}

impl ::ttrpc::MethodHandler for GetManifestMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, aether, GetManifestRequest, get_manifest);
        Ok(())
    }
}

struct StreamLogsMethod {
    service: Arc<dyn AetherAgent + Send + Sync>,
}

impl ::ttrpc::MethodHandler for StreamLogsMethod {
    fn handler(&self, ctx: ::ttrpc::TtrpcContext, req: ::ttrpc::Request) -> ::ttrpc::Result<()> {
        ::ttrpc::request_handler!(self, ctx, req, aether, LogRequest, stream_logs);
        Ok(())
    }
}

pub trait AetherAgent {
    fn register_add_in(&self, _ctx: &::ttrpc::TtrpcContext, _: super::aether::AddInRequest) -> ::ttrpc::Result<super::aether::AddInResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/aether.AetherAgent/RegisterAddIn is not supported".to_string())))
    }
    fn materialize_path(&self, _ctx: &::ttrpc::TtrpcContext, _: super::aether::MaterializeRequest) -> ::ttrpc::Result<super::aether::MaterializeResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/aether.AetherAgent/MaterializePath is not supported".to_string())))
    }
    fn update_proxy_rules(&self, _ctx: &::ttrpc::TtrpcContext, _: super::aether::ProxyRules) -> ::ttrpc::Result<super::empty::Empty> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/aether.AetherAgent/UpdateProxyRules is not supported".to_string())))
    }
    fn get_manifest(&self, _ctx: &::ttrpc::TtrpcContext, _: super::aether::GetManifestRequest) -> ::ttrpc::Result<super::aether::ManifestResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/aether.AetherAgent/GetManifest is not supported".to_string())))
    }
    fn stream_logs(&self, _ctx: &::ttrpc::TtrpcContext, _: super::aether::LogRequest) -> ::ttrpc::Result<super::aether::LogResponse> {
        Err(::ttrpc::Error::RpcStatus(::ttrpc::get_status(::ttrpc::Code::NOT_FOUND, "/aether.AetherAgent/StreamLogs is not supported".to_string())))
    }
}

pub fn create_aether_agent(service: Arc<dyn AetherAgent + Send + Sync>) -> HashMap<String, Box<dyn ::ttrpc::MethodHandler + Send + Sync>> {
    let mut methods = HashMap::new();

    methods.insert("/aether.AetherAgent/RegisterAddIn".to_string(),
                    Box::new(RegisterAddInMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/aether.AetherAgent/MaterializePath".to_string(),
                    Box::new(MaterializePathMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/aether.AetherAgent/UpdateProxyRules".to_string(),
                    Box::new(UpdateProxyRulesMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/aether.AetherAgent/GetManifest".to_string(),
                    Box::new(GetManifestMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods.insert("/aether.AetherAgent/StreamLogs".to_string(),
                    Box::new(StreamLogsMethod{service: service.clone()}) as Box<dyn ::ttrpc::MethodHandler + Send + Sync>);

    methods
}
